# Generated by Django 5.2.6 on 2025-09-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaIe',
            fields=[
                ('id_caja_ie', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField()),
                ('nonto', models.DecimalField(decimal_places=5, max_digits=10)),
                ('descripcion', models.CharField(blank=True, null=True)),
                ('url_boelta', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'caja_ie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField()),
                ('direccion', models.CharField()),
                ('latitud', models.CharField(blank=True, null=True)),
                ('longitud', models.CharField(blank=True, null=True)),
                ('numero', models.CharField()),
                ('frecuencia', models.CharField()),
                ('referencia', models.CharField()),
                ('sector_lugar', models.CharField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado', models.CharField()),
            ],
            options={
                'db_table': 'estado_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('entrada', models.TimeField()),
                ('salida', models.TimeField()),
                ('inicio_break', models.TimeField(blank=True, null=True)),
                ('fin_break', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('operativos', models.IntegerField()),
                ('necesitan_reparacion', models.IntegerField()),
                ('rotos', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('nom_modulo', models.CharField()),
            ],
            options={
                'db_table': 'modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('yape', models.IntegerField()),
                ('efectivo', models.IntegerField()),
            ],
            options={
                'db_table': 'pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_p', models.CharField()),
                ('apellido_p', models.CharField()),
                ('dni_p', models.CharField()),
                ('direccion', models.CharField()),
                ('url_dni', models.CharField(blank=True, null=True)),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField()),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Retorno',
            fields=[
                ('id_retorno', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total_cancelado', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'retorno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id_salida', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('multiplicar_por', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_cancelar', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
            options={
                'db_table': 'salida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tipo_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_cliente', models.CharField()),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDetalle',
            fields=[
                ('id_tipo_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_detalle', models.CharField()),
            ],
            options={
                'db_table': 'tipo_detalle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_p', models.CharField()),
                ('unidad_medida', models.CharField()),
                ('contenido', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id_tipo_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tt', models.CharField()),
            ],
            options={
                'db_table': 'tipo_trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUserModulo',
            fields=[
                ('id_tipo_user_modulo', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tipo_user_modulo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id_tipo_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField()),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('sueldo', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'trabajador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('nom_user', models.CharField()),
                ('pass_user', models.CharField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_v', models.DecimalField(decimal_places=5, max_digits=10)),
                ('cobra_de', models.DecimalField(decimal_places=5, max_digits=10)),
                ('total_cancelar', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha', models.DateField()),
                ('hora', models.DateField()),
                ('total_cancelado', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            options={
                'db_table': 'venta',
                'managed': False,
            },
        ),
    ]
