# Generated by Django 5.2.6 on 2025-10-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoSalida',
            fields=[
                ('id_estado_salida', models.AutoField(primary_key=True, serialize=False)),
                ('nom_estado_salida', models.CharField()),
            ],
            options={
                'db_table': 'estado_salida',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'managed': True},
        ),
    ]
