# Generated by Django 5.2.6 on 2025-10-21 22:30

from django.db import migrations, models
import django.db.models.deletion

def crear_estado_default(apps, schema_editor):
    EstadoSalida = apps.get_model('database', 'EstadoSalida')
    EstadoPago = apps.get_model('database', 'EstadoPago')
    
    # Crear estados por defecto si no existen
    EstadoSalida.objects.get_or_create(
        id_estado_salida=1, 
        defaults={'nom_estado_salida': 'En ruta'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_estadosalida_alter_salida_options'),
    ]

    operations = [
        migrations.RunPython(crear_estado_default),
        migrations.AddField(
            model_name='salida',
            name='id_estado_salida',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to='database.estadosalida',
                db_column='id_estado_salida'
            ),
            preserve_default=False,
        ),
    ]